[project]
name = "ai-resume-gateway"
version = "0.1.0"
description = "FastAPI gateway for AI Resume Assistant"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.112",
  "uvicorn[standard]>=0.30",
  "httpx>=0.27",
  "pydantic>=2.7",
]
