name: Orchestrator CI (CLI fallback)

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  orchestrator-ci:
    runs-on: ubuntu-latest
    env:
      ORCHESTRATOR_PLUGIN_MODE: cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install Rust audit tool
        run: |
          cargo install cargo-audit || true

      - name: Python environment (optional)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit (optional)
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit || true

      - name: Install JS deps (workspace)
        run: |
          pnpm install -w || npm install -w

      - name: Build JS
        run: |
          pnpm run build || npm run build

      - name: Build Rust
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
          cargo test --quiet

      - name: Phase checks - PLAN (CLI fallbacks)
        run: |
          bash orchestrator/plugins.runtime.sh plan || true
          bash orchestrator/hooks/lint_phase.sh plan

      - name: Phase checks - IMPLEMENT (CLI fallbacks)
        run: |
          bash orchestrator/plugins.runtime.sh implement || true
          bash orchestrator/hooks/lint_phase.sh implement

      - name: Phase checks - ANALYZE (CLI fallbacks)
        run: |
          bash orchestrator/plugins.runtime.sh analyze || true
          bash orchestrator/hooks/lint_phase.sh analyze

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: orchestrator-reports
          path: |
            reports/security/**
            reports/tests/**
            reports/compliance/**
          if-no-files-found: ignore
